SectionDevice."Headphones" {
    Comment "Headphones"
    Type "Audio/Sink"
    ConflictingDevice [
        "Speaker"
        "MainMic"
    ]

    Value {
        PlaybackMixerElem "DAC1"
        PlaybackVolume "DAC1 Playback Volume"
        PlaybackSwitch "DAC1 Playback Switch"
    }

    EnableSequence [
        cset "name='DAC1 Playback Switch' on"
    ]
    DisableSequence [
        cset "name='DAC1 Playback Switch' off"
    ]
}
